use anyhow::Result;
use async_trait::async_trait;

/// Trait for Turnstile CAPTCHA verification to enable mocking in tests
///
/// This trait defines the interface for verifying Cloudflare Turnstile tokens.
/// Implementations can be real (making HTTP calls to Cloudflare) or mocked for testing.
#[async_trait]
pub trait TurnstileServiceTrait: Send + Sync {
    /// Verify a Turnstile token
    ///
    /// # Arguments
    /// * `token` - The token generated by the Turnstile widget on the frontend
    /// * `ip_address` - The IP address of the user making the request
    ///
    /// # Returns
    /// * `Ok(true)` - Token is valid and user passed the challenge
    /// * `Ok(false)` - Token is invalid, expired, or failed verification
    /// * `Err(_)` - Network error or API failure (caller should decide fail-open vs fail-closed)
    async fn verify_token(&self, token: &str, ip_address: &str) -> Result<bool>;
}
